name: confgurable_ablation
channels:
  - conda-forge
  - defaults
dependencies:
  - cairo=1.16.0
  - graphviz=2.49.0
  - jupyterlab=3.1.9
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - numba=0.53.1
  - numpy=1.21.2
  - pip=21.2.4
  - scipy=1.7.1
  - seaborn=0.11.2
  - pip:
    - arviz==0.11.2
    - bambi==0.6.1
    - dill==0.3.4
    - matplotlib==3.4.3
    - pandas==1.3.2
    - ptable==0.9.2
    - pymc3==3.11.4
    - statsmodels==0.12.2